/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MyQueueRouteImport } from './routes/my-queue'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StaffAnalyticsRouteImport } from './routes/staff/analytics'
import { Route as StaffDashboardRouteImport } from './routes/staff/dashboard'
import { Route as StaffLoginRouteImport } from './routes/staff/login'
import { Route as StaffServicesRouteImport } from './routes/staff/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQueueRoute = MyQueueRouteImport.update({
  id: '/my-queue',
  path: '/my-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAnalyticsRoute = StaffAnalyticsRouteImport.update({
  id: '/staff/analytics',
  path: '/staff/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/staff/dashboard',
  path: '/staff/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffServicesRoute = StaffServicesRouteImport.update({
  id: '/staff/services',
  path: '/staff/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/join': typeof JoinRoute
  '/my-queue': typeof MyQueueRoute
  '/services': typeof ServicesRoute
  '/staff/analytics': typeof StaffAnalyticsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/services': typeof StaffServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/join': typeof JoinRoute
  '/my-queue': typeof MyQueueRoute
  '/services': typeof ServicesRoute
  '/staff/analytics': typeof StaffAnalyticsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/services': typeof StaffServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/join': typeof JoinRoute
  '/my-queue': typeof MyQueueRoute
  '/services': typeof ServicesRoute
  '/staff/analytics': typeof StaffAnalyticsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/services': typeof StaffServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/join'
    | '/my-queue'
    | '/services'
    | '/staff/analytics'
    | '/staff/dashboard'
    | '/staff/login'
    | '/staff/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/join'
    | '/my-queue'
    | '/services'
    | '/staff/analytics'
    | '/staff/dashboard'
    | '/staff/login'
    | '/staff/services'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/join'
    | '/my-queue'
    | '/services'
    | '/staff/analytics'
    | '/staff/dashboard'
    | '/staff/login'
    | '/staff/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  JoinRoute: typeof JoinRoute
  MyQueueRoute: typeof MyQueueRoute
  ServicesRoute: typeof ServicesRoute
  StaffAnalyticsRoute: typeof StaffAnalyticsRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StaffServicesRoute: typeof StaffServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-queue': {
      id: '/my-queue'
      path: '/my-queue'
      fullPath: '/my-queue'
      preLoaderRoute: typeof MyQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/analytics': {
      id: '/staff/analytics'
      path: '/staff/analytics'
      fullPath: '/staff/analytics'
      preLoaderRoute: typeof StaffAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/services': {
      id: '/staff/services'
      path: '/staff/services'
      fullPath: '/staff/services'
      preLoaderRoute: typeof StaffServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  JoinRoute: JoinRoute,
  MyQueueRoute: MyQueueRoute,
  ServicesRoute: ServicesRoute,
  StaffAnalyticsRoute: StaffAnalyticsRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffLoginRoute: StaffLoginRoute,
  StaffServicesRoute: StaffServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
